### ISSUE TITLE
Examples outdated

### ISSUE THREAD

**Issue by UweBonnes** [OLIMEX/NB-IoT#14]
The examples under NB-IoT/SOFTWARE/BC66 are outdated and do not compile with recent platformio. Use github.com:Wiz-IO/platformio-quectel-examples instead.

**Comment by DanKoloff** [comment]
Did you check the instructions here:

https://github.com/OLIMEX/NB-IoT/blob/master/SOFTWARE/NB-IoT-DevKit-PlatformIO-installation.pdf
