### ISSUE TITLE
Linux Flashing Tools Don't Work With Current Version Of Linux

### ISSUE THREAD

**Issue by spit4520** [OLIMEX/NB-IoT#3]
Hello,

I receive errors dealing with `Boot answer` and `echo cmd` when trying to run the scripts. I have all of the needed supporting libraries and am running python2. I am currently using `Ubuntu 18.04.3` as my platform. I am attempting to write over the application and restore the AT command interface to the standard serial com port, as I outlined in my previous issue `/dev/ttyUSB0` is the only com port and there is not a second dedicated one for AT commands like on windows.

Please let me know if there is any unit testing I can do on my side. Once we have a working set of scripts made. I would like to contribute to the wiki to help others in the future.

Best,

Scott

**Comment by DanKoloff** [comment]
Try this and let us know how it goes: https://github.com/OLIMEX/NB-IoT/tree/master/SOFTWARE/AT_restore_tool
