### ISSUE TITLE
Getting error "Wrong SN number"

### ISSUE THREAD

**Issue by ASL07** [OLIMEX/NB-IoT#4]
Hi, 

I have installed the drivers using the https://github.com/OLIMEX/ch340-dkms repo.
The install_ch340.sh script provided on this repo fails with the error `Expected ( at line 19`

The BC66 devkit is connected to the pc and detected as a serial port (ttyUSB0)
When I run REPAIR.sh I get the following error
`Wrong SN number`

Could you give some clues on why it is failing? 
Thanks

**Comment by kalata23** [comment]
Hi, ASL07,
Unfortunately there was issue with README not displaying the parrameters of 'REPAIR.sh' which I think is the case of your issue.
Syntax is: 

`./REPAIR.sh SN IMEI`

Both **SN** and **IMEI** are written on the metal plate of the BC66 module. 

Command execution example:

`./REPAIR.sh MPA19BS1F020305 86787890123456123`

Please keep a note, that SN and IMEI numbers  you pass to the script file, must match with the ones written on the metal plate.

Kaloyan

**Comment by ASL07** [comment]
Hi,
Do I have to press reset key or power key when I run the script?
I am pressing reset key after starting the script, but it fails most of the times. 
I was able to get `Removing app.......................[ DONE ]` only once, and I always get ` Restoring nvdm.....................[ FAILED ]
`

**Comment by ASL07** [comment]
> Hi,
> Do I have to press reset key or power key when I run the script?
> I am pressing reset key after starting the script, but it fails most of the times.
> I was able to get `Removing app.......................[ DONE ]` only once, and I always get `Restoring nvdm.....................[ FAILED ]`

It works now. 
We need to press reset AFTER a couple of seconds after the script outputs `Removing app......................` or `Restoring nvdm.....................` . If the reset button is pressed too soon then it fails

**Comment by kalata23** [comment]
Can you tell me the revision of the board that u have? You shouldn't be forced to press RST button.

**Comment by ASL07** [comment]
Yes, if you tell me where to find it... The only thing I can see is 2019

**Comment by kalata23** [comment]
> Yes, if you tell me where to find it... The only thing I can see is 2019

 It should be next to the BC66 module.

**Comment by ASL07** [comment]
> > Yes, if you tell me where to find it... The only thing I can see is 2019
> 
> It should be next to the BC66 module.

It's Rev B

**Comment by kalata23** [comment]
No need to manually reset the board with Rev B. The flash tool resets the board. Maybe you have bad USB connection (bad usb cable or not properly plugged).  Also to avoid reset issue, you can try to disconnect the board and connect it seconds before executing the REPAIR.sh script. Keep in mind that all Serial connections with the board should be closed before executing REPAIR.sh.


Kaloyan

**Comment by ASL07** [comment]
I have tested this again
Disconnecting the board and reconnecting it just before the script is run helps, but it fails sometimes.
If the board is already connected, then I have to press the reset button for it to work

**Comment by ASL07** [comment]
#3 
Hi,
Now the restore.sh script does not work at all
Previously, connecting the USB would make it work intermittently, but right now, it does not work at all.

Is there a way to restore AT functionality using IoT flash tool on Windows, or even Qflash?

I have a device backup but whenever I try to flash it with Qflash or flashtool I get "Format error"

**Comment by kalata23** [comment]
> #3
> Hi,
> Now the restore.sh script does not work at all
> Previously, connecting the USB would make it work intermittently, but right now, it does not work at all.
> 
> Is there a way to restore AT functionality using IoT flash tool on Windows, or even Qflash?
> 
> I have a device backup but whenever I try to flash it with Qflash or flashtool I get "Format error"

What version of the firmware did you use before uploading your own application?
Does restore.sh give you any error messages?
