### ISSUE TITLE
USB UART AT command interface becomes unresponsive after some time

### ISSUE THREAD

**Issue by ASL07** [OLIMEX/NB-IoT#5]
Hi, 

I am testing this board in AT command mode.
I have it connected to my computer through USB and I am sending AT commands to it using the OS X screen tool
After several minutes, the modem becomes unresponsive, it doesn't respond to any characters sent to the USB port

If I reset the board using the reset button, the USB interface works again

**Comment by DanKoloff** [comment]
Maybe some sleep mode gets enabled? Not sure what is set by default. Try to disable it with:

AT+QSCLK=0

**Comment by ASL07** [comment]
That was it, I disabled sleep mode with Ql_SleepDisable() and now it's not happening.
Thanks!
