### ISSUE TITLE
Board is not powering up unless USB is connected

### ISSUE THREAD

**Issue by ASL07** [OLIMEX/NB-IoT#9]
Hello,

I am having a strange issue with my board.

I followed this and have connected position 1-2 and disconnected position 2-3 of the jumper, in order to set VCCB as power input
![image](https://user-images.githubusercontent.com/4049435/91014202-43736c80-e5e9-11ea-88e4-f2d7396ee73a.png)

I expect the board to power on whenever I connect 5V to VCCB, but it doesn't power up unless I connect the USB as well

I tried also connecting a battery but nothing changes either

**Comment by DanKoloff** [comment]
Did you provide 5V to pin 1 +5V_EXT too? The jumpers and VCCB power input set the buffers but you still need to provide input +5V_EXT. You can use the same 5V source for both VCCB and +5V_EXT.

Important! When you provide 5V to VCCB and 5V to the input all GPIOs would become 5V. Make sure you don't have 3.3V peripherals connected to GPIOs or they might get damaged.

**Comment by ASL07** [comment]
Hi,
I should have mentioned. 
Yes am providing 5V to both 5V_EXT and VCCB
And yes, I want all GPIO to have 5V logic

**Comment by ASL07** [comment]
Sorry, my fault, it was a power supply issue. I switched to a more reliable one and now it works.
